In [3]:
import torch
print(torch.__version__)

2.10.0+cu128


In [4]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"using GPU: {torch.cuda.get_device_name(0)}")

else:
  print("GPU is not avaiable using CPU.")

GPU is available!
using GPU: Tesla T4


## Creating a Tensor

In [5]:
# Using Empty
torch.empty(2,3) # Creating an Tensor using Empty Function i.e. A Tensor(with default) values will be created.

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.4013e-45, 0.0000e+00]])

In [6]:
# Using Zeros
torch.zeros(2,3) # Tensor with all 0s.

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# Using Ones
torch.ones(2,3) # Tensor with all 1s.


tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# Using rand
torch.rand(2,3) # Tensor with all Random Values.


tensor([[0.5340, 0.3638, 0.1150],
        [0.1972, 0.8704, 0.5012]])

In [9]:
# Using manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
# Using tensor
torch.tensor([[1,2,3], [4,5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
# other ways to create a tensor

# using arange
print("using arange:", torch.arange(0,10)) # Creating a Tensor from 0 to 9.

# using linspace
print("using  linspace:", torch.linspace(0,10,10))

# using eye
print("using eye:", torch.eye(5)) # Creating a 5 * 5 Identity Matrix Tensor.

# using full
print("using full:", torch.full((3,3), 5)) # Creating a 3 * 3 Tensor of 5.


using arange: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using  linspace: tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye: tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full: tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [12]:
x = torch.tensor([[1,2,3], [4, 5, 6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [13]:
x.shape

torch.Size([2, 3])

In [14]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [22]:
torch.rand_like(x, dtype = torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data - Types

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                     

In [16]:
# Find the Data - Type
x.dtype

torch.int64

In [17]:
# Assign Data - Type
torch.tensor([1, 0, 2, 0, 3, 0], dtype = torch.int32)

tensor([1, 0, 2, 0, 3, 0], dtype=torch.int32)

In [18]:
# Assign Data - Type
torch.tensor([1, 0, 2, 0, 3, 0], dtype = torch.float64)

tensor([1., 0., 2., 0., 3., 0.], dtype=torch.float64)

In [19]:
# using to() - Change the data - type of tensor
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Mathematical Operations associated with Tensor

## 1. Scalar Operation

In [23]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [24]:
# Addition Operation

x + 2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [26]:
# Subraction operation
x - 2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [25]:
# Multiplication Operation
x *2

tensor([[1.4235, 1.5752],
        [0.8366, 1.8028]])

In [27]:
# Divion Operation(float)
x / 2

tensor([[0.3559, 0.3938],
        [0.2092, 0.4507]])

In [29]:
# int Division
(x *100)//2

tensor([[35., 39.],
        [20., 45.]])

In [32]:
# Mod Operation
((x *100)//3)%2


tensor([[1., 0.],
        [1., 0.]])

In [33]:
# Power Operation
x ** 2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

## 2. Element - Wise Operation in Tensors

In [34]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [35]:
# Addition Operation
a + b
print(a + b)

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])


In [37]:
# Subraction Operation
a - b
print(a -b)

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])


In [38]:
# Division Operator(float)
a /b

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [40]:
# Power Operation
a ** b
print(a **b)

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])


In [41]:
# Mod operation
a % b
print(a % b)

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])


In [42]:
c = torch.tensor([1, - 2, 3, -4])

In [43]:
# abs
torch.abs(x)

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [44]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [45]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [46]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [47]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [48]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [49]:
# clamp
torch.clamp(d, min = 2, max = 3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## 3. Reduction Operation

In [50]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [51]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([15.,  9.])

In [52]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([4., 0., 8.])

In [53]:
# median
torch.median(e)

tensor(0.)

In [54]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [55]:
# product
torch.prod(e)

tensor(0.)

In [56]:
# standard deviation
torch.std(e)

tensor(4.4272)

In [57]:
# variance
torch.var(e)

tensor(19.6000)

In [58]:
# argmax
torch.argmax(e)

tensor(5)

In [59]:
# argmin
torch.argmin(e)

tensor(1)

## 4. Matrix operations

In [60]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [61]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[ 87, 119],
        [ 65,  99]])

In [62]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [63]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [64]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 9., 8.],
        [9., 7., 9.],
        [2., 6., 7.]])

In [65]:
# determinant
torch.det(h)

tensor(-110.)

In [66]:
# inverse
torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

## 5. Comparison operations

In [67]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [68]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

## 6. Special functions

In [69]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[3., 3., 5.],
        [0., 6., 4.]])

In [70]:
# log
torch.log(k)

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863]])

In [71]:
# exp
torch.exp(k)

tensor([[ 20.0855,  20.0855, 148.4132],
        [  1.0000, 403.4288,  54.5981]])

In [72]:
# sqrt
torch.sqrt(k)

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000]])

In [73]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9526, 0.9526, 0.9933],
        [0.5000, 0.9975, 0.9820]])

In [74]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9526, 0.0474, 0.7311],
        [0.0474, 0.9526, 0.2689]])

In [75]:
# relu
torch.relu(k)

tensor([[3., 3., 5.],
        [0., 6., 4.]])

##7. Inplace Operations

In [76]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [77]:
m.add_(n)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [78]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [79]:
torch.relu(m)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [80]:
m.relu_()

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [81]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

## Copying a Tensor

In [82]:
a = torch.rand(2,3)
a

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [83]:
b = a

In [84]:
b


tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [85]:
a[0][0] = 0

In [86]:
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [87]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [88]:
id(a)

137462565192960

In [89]:
id(b)

137462565192960

In [90]:
b = a.clone()

In [95]:
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [96]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [97]:
a[0][0] = 10

In [98]:
a

tensor([[10.0000,  0.2324,  0.9141],
        [ 0.7668,  0.1659,  0.4393]])

In [99]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [100]:
id(a)


137462565192960

In [101]:
id(b)

137462565036080