# PyTorch Tutorial - Part 1: Beginner's Complete Guide



- We go through PyTorch step by step, explaining every line.

Topics covered:
1. What is PyTorch?
2. Tensors
3. Autograd (automatic gradient calculation)
4. Neural Networks
5. Loss Functions and Optimizers
6. The Training Loop
7. Datasets and DataLoaders
8. Saving and Loading Models



## Section 1 - What is PyTorch?

PyTorch is a free, open-source library made by Facebook (Meta) for building and training neural networks.

Without PyTorch, writing neural networks from scratch in pure math would take thousands of lines of code.
PyTorch gives us ready-made tools so we can focus on building, not implementing basic math.

What PyTorch does:
1. Stores data in special arrays called tensors (like NumPy, but can run on GPU)
2. Automatically calculates gradients needed for training
3. Provides pre-built neural network layers

In [1]:
# Install PyTorch if not already installed (uncomment the line below)
# !pip install torch torchvision

import torch               # main PyTorch package
import torch.nn as nn      # neural network layers and utilities
import torch.nn.functional as F  # activation functions like relu, sigmoid
import torch.optim as optim      # optimizers like Adam and SGD
import numpy as np
import matplotlib.pyplot as plt

print('PyTorch version:', torch.__version__)

# Check if a GPU is available.
# GPU = Graphics Processing Unit. It makes training much faster.
# CUDA is NVIDIA's system that lets PyTorch use the GPU.
# If you see 'cpu' here, everything still works, just a bit slower.
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print('Using device:', device)


PyTorch version: 2.10.0+cpu
Using device: cpu


## Section 2 - Tensors: The Building Blocks of PyTorch

A tensor is just a container for numbers, exactly like a NumPy array, but with two extra abilities:
1. It can run on a GPU (much faster for large data)
2. It can track gradients (needed for training neural networks)

Types of tensors:
- 0D tensor (scalar): a single number, like 25
- 1D tensor (vector): a list of numbers, like [85, 90, 78]
- 2D tensor (matrix): a table of numbers, like a spreadsheet
- 3D tensor: a stack of matrices, like an RGB image (height x width x color channels)
- 4D tensor: a batch of images (batch_size x height x width x channels)

In [2]:
# Creating tensors

# Method 1: from a Python list
t1 = torch.tensor([1.0, 2.0, 3.0])
print('1D Tensor:', t1)
print('  Shape:', t1.shape)    # shape tells us the dimensions
print('  Data type:', t1.dtype) # what kind of numbers are stored

# Method 2: 2D tensor (matrix) from a nested list
t2 = torch.tensor([[1.0, 2.0, 3.0],
                    [4.0, 5.0, 6.0]])
print('\n2D Tensor:')
print(t2)
print('  Shape:', t2.shape)  # (2, 3) means 2 rows and 3 columns

# Method 3: tensor of all zeros
zeros = torch.zeros(3, 4)  # 3 rows, 4 columns
print('\nZeros tensor (3x4):')
print(zeros)

# Method 4: tensor of all ones
ones = torch.ones(2, 3)
print('\nOnes tensor (2x3):')
print(ones)

# Method 5: random tensor with values between 0 and 1
# We use random tensors often to initialize neural network weights
rand = torch.rand(3, 3)
print('\nRandom tensor (3x3):')
print(rand)

# Method 6: random tensor with normal distribution (mean=0, std=1)
randn = torch.randn(3, 3)
print('\nNormal random tensor (3x3):')
print(randn)

# Method 7: range tensor, like Python's range()
r = torch.arange(0, 10, 2)  # start=0, stop=10, step=2
print('\nRange tensor:', r)

# Method 8: convert a NumPy array to a tensor
np_array = np.array([10, 20, 30, 40])
from_numpy = torch.from_numpy(np_array)
print('\nFrom NumPy:', from_numpy)


1D Tensor: tensor([1., 2., 3.])
  Shape: torch.Size([3])
  Data type: torch.float32

2D Tensor:
tensor([[1., 2., 3.],
        [4., 5., 6.]])
  Shape: torch.Size([2, 3])

Zeros tensor (3x4):
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Ones tensor (2x3):
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Random tensor (3x3):
tensor([[0.3020, 0.5581, 0.8794],
        [0.4023, 0.2855, 0.3855],
        [0.2377, 0.5654, 0.0371]])

Normal random tensor (3x3):
tensor([[ 0.7679, -2.0725,  0.1449],
        [ 0.5351,  0.4502, -0.8382],
        [ 1.0886, -0.5225,  0.6134]])

Range tensor: tensor([0, 2, 4, 6, 8])

From NumPy: tensor([10, 20, 30, 40], dtype=torch.int32)


In [3]:
# Tensor properties
x = torch.randn(4, 5)  # 4 rows, 5 columns, random values

print('Tensor x:')
print(x)
print()
print('Shape:', x.shape)          # size of each dimension
print('Dimensions:', x.ndim)      # how many dimensions
print('Data type:', x.dtype)      # float32 by default
print('Device:', x.device)        # cpu or cuda
print('Total elements:', x.numel()) # total count: 4 * 5 = 20


Tensor x:
tensor([[ 0.9532, -0.5006,  2.2481,  0.6548,  0.1054],
        [ 2.0881, -0.4112,  1.0536, -0.6319, -0.0459],
        [ 0.3094,  0.1914,  0.2320,  1.4951,  1.0232],
        [-2.0356, -1.7262,  1.1106,  2.1173,  1.0320]])

Shape: torch.Size([4, 5])
Dimensions: 2
Data type: torch.float32
Device: cpu
Total elements: 20


In [4]:
# Tensor operations

a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

print('a + b =', a + b)     # element-wise addition
print('a - b =', a - b)     # subtraction
print('a * b =', a * b)     # element-wise multiplication (NOT matrix multiply)
print('a / b =', a / b)     # division
print('a * 2 =', a * 2)     # scalar operations apply to every element
print('a ** 2 =', a ** 2)   # power
print('Sum of a:', a.sum())  # add all elements
print('Mean of a:', a.mean()) # average
print('Max:', a.max(), ' Min:', a.min())

# Matrix multiplication - very important in neural networks!
m1 = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
m2 = torch.tensor([[5.0, 6.0], [7.0, 8.0]])

result = torch.matmul(m1, m2)  # matrix multiplication
print('\nMatrix multiplication result:')
print(result)
# You can also write: m1 @ m2 (same thing, shorter)
print('Same with @ operator:')
print(m1 @ m2)


a + b = tensor([5., 7., 9.])
a - b = tensor([-3., -3., -3.])
a * b = tensor([ 4., 10., 18.])
a / b = tensor([0.2500, 0.4000, 0.5000])
a * 2 = tensor([2., 4., 6.])
a ** 2 = tensor([1., 4., 9.])
Sum of a: tensor(6.)
Mean of a: tensor(2.)
Max: tensor(3.)  Min: tensor(1.)

Matrix multiplication result:
tensor([[19., 22.],
        [43., 50.]])
Same with @ operator:
tensor([[19., 22.],
        [43., 50.]])


In [5]:
# Reshaping tensors
# Reshaping changes the shape without changing the data

original = torch.arange(12)  # [0, 1, 2, ..., 11]
print('Original:', original)
print('Shape:', original.shape)

# .view() reshapes (requires contiguous memory)
as_3x4 = original.view(3, 4)
print('\nReshaped to 3x4:')
print(as_3x4)

# .reshape() is the safer version
as_2x6 = original.reshape(2, 6)
print('\nReshaped to 2x6:')
print(as_2x6)

# Use -1 to let PyTorch calculate one dimension automatically
auto = original.reshape(4, -1)  # 4 rows, figure out columns
print('\nReshaped to 4x? (auto):')
print(auto)  # PyTorch gives 4x3

# .flatten() collapses everything into a 1D vector
flat = as_3x4.flatten()
print('\nFlattened:', flat)

# .unsqueeze() adds a dimension, .squeeze() removes one of size 1
t = torch.tensor([1.0, 2.0, 3.0])   # shape: [3]
t_exp = t.unsqueeze(0)               # shape becomes [1, 3]
print('\nAfter unsqueeze(0):', t_exp.shape)
t_back = t_exp.squeeze(0)            # back to [3]
print('After squeeze(0):', t_back.shape)


Original: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Shape: torch.Size([12])

Reshaped to 3x4:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Reshaped to 2x6:
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

Reshaped to 4x? (auto):
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

Flattened: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

After unsqueeze(0): torch.Size([1, 3])
After squeeze(0): torch.Size([3])


In [6]:
# Moving tensors to GPU
# A GPU has thousands of tiny cores, perfect for neural network math in parallel.
# Moving to GPU can make training 10x to 100x faster.

print('Current device:', device)

cpu_tensor = torch.randn(3, 3)
print('CPU tensor device:', cpu_tensor.device)

# Move to GPU (or keep on CPU if no GPU available)
gpu_tensor = cpu_tensor.to(device)
print('After .to(device):', gpu_tensor.device)

# IMPORTANT: all tensors in one operation must be on the SAME device.
# You cannot add a CPU tensor and a GPU tensor directly.

# Best practice: create tensors directly on the target device
t = torch.randn(4, 4, device=device)
print('\nCreated directly on device:', t.device)


Current device: cpu
CPU tensor device: cpu
After .to(device): cpu

Created directly on device: cpu


## Section 3 - Autograd: Automatic Gradient Calculation

To train a neural network we need gradients - numbers that tell us how to adjust the model's weights to reduce the loss.

Calculating gradients by hand is very hard. PyTorch does it for us automatically.
This system is called Autograd.

How it works:
1. You tell PyTorch to track a tensor: set requires_grad=True
2. You do calculations with that tensor
3. You call .backward() on the result
4. PyTorch fills in the .grad field for all tracked tensors automatically

The gradient tells us: if I increase this weight by a tiny amount, how much does the loss change?
We use that information to move the weight in the direction that reduces the loss.

In [7]:
# Basic autograd example

# requires_grad=True tells PyTorch to track all operations on this tensor
x = torch.tensor(3.0, requires_grad=True)

# Do some math
y = x ** 2       # y = x squared
z = y + 2 * x   # z = x^2 + 2x

print('x =', x.item())
print('z =', z.item())   # z = 9 + 6 = 15

# .backward() computes gradients of z with respect to x
z.backward()

# x.grad now contains dz/dx
# Math: dz/dx = 2x + 2 = 2*3 + 2 = 8
print('Gradient dz/dx =', x.grad.item())  # should be 8


x = 3.0
z = 15.0
Gradient dz/dx = 8.0


In [8]:
# Autograd with multiple variables

a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)

# f = a^2 + a*b + b^2
f = a**2 + a*b + b**2

f.backward()

# df/da = 2a + b = 2*2 + 3 = 7
# df/db = a + 2b = 2 + 2*3 = 8
print('df/da =', a.grad.item())  # 7
print('df/db =', b.grad.item())  # 8

# torch.no_grad() - use this during inference (prediction) and validation
# It disables gradient tracking, which saves memory and runs faster
with torch.no_grad():
    result = a * b   # no gradient is tracked here
print('\nresult.requires_grad inside no_grad:', result.requires_grad)  # False


df/da = 7.0
df/db = 8.0

result.requires_grad inside no_grad: False


## Section 4 - Neural Networks

A neural network is a stack of mathematical operations (layers) that transforms input data into predictions.

In PyTorch, every neural network is a class that inherits from nn.Module.
You always write two methods:
- __init__: define and store your layers here
- forward: describe how data flows through the layers

The most basic layer is nn.Linear(in, out), which does: output = input * weight + bias

Common activation functions (applied after linear layers to add non-linearity):
- ReLU: output = max(0, input) - the most common choice
- Sigmoid: squashes output to (0, 1) - used for binary output
- Tanh: squashes output to (-1, 1)

In [9]:
# Building with nn.Sequential - the simplest way
# Just list layers in order. Data goes in one end and comes out the other.

model = nn.Sequential(
    nn.Linear(10, 64),   # first hidden layer: 10 inputs, 64 outputs
    nn.ReLU(),           # activation: replace negatives with 0
    nn.Dropout(0.2),     # randomly turn off 20% of neurons during training
                         # this prevents memorizing training data (overfitting)
    nn.Linear(64, 32),   # second hidden layer
    nn.ReLU(),
    nn.Dropout(0.2),
    nn.Linear(32, 3)     # output layer: 3 class scores
)

print('Model:')
print(model)

# Count learnable parameters
total_params = sum(p.numel() for p in model.parameters())
print(f'\nTotal parameters: {total_params:,}')

# Test: pass a batch of 8 samples through, each with 10 features
sample_batch = torch.randn(8, 10)
output = model(sample_batch)
print(f'\nInput shape: {sample_batch.shape}')  # [8, 10]
print(f'Output shape: {output.shape}')         # [8, 3]


Model:
Sequential(
  (0): Linear(in_features=10, out_features=64, bias=True)
  (1): ReLU()
  (2): Dropout(p=0.2, inplace=False)
  (3): Linear(in_features=64, out_features=32, bias=True)
  (4): ReLU()
  (5): Dropout(p=0.2, inplace=False)
  (6): Linear(in_features=32, out_features=3, bias=True)
)

Total parameters: 2,883

Input shape: torch.Size([8, 10])
Output shape: torch.Size([8, 3])


In [10]:
# Building with a custom nn.Module class
# This gives you more control over how data flows.

# Rules:
# 1. Always inherit from nn.Module
# 2. Always define __init__ - create your layers here
# 3. Always define forward - describe the data flow

class MyFirstNetwork(nn.Module):

    def __init__(self, input_size, hidden_size, output_size):
        # Always call the parent constructor first
        super(MyFirstNetwork, self).__init__()

        # Define layers and store them as attributes
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.bn1 = nn.BatchNorm1d(hidden_size)  # normalizes for stable training

        self.fc2 = nn.Linear(hidden_size, hidden_size // 2)
        self.bn2 = nn.BatchNorm1d(hidden_size // 2)

        self.fc3 = nn.Linear(hidden_size // 2, output_size)  # output layer

        self.dropout = nn.Dropout(p=0.3)  # 30% chance of dropping a neuron

    def forward(self, x):
        # This defines the data flow through the network
        # It is called automatically when you do: model(input)

        x = self.fc1(x)      # linear transformation
        x = self.bn1(x)      # normalize
        x = F.relu(x)        # activate
        x = self.dropout(x)  # randomly drop neurons

        x = self.fc2(x)
        x = self.bn2(x)
        x = F.relu(x)
        x = self.dropout(x)

        x = self.fc3(x)  # output layer - no activation here

        return x


model = MyFirstNetwork(input_size=20, hidden_size=64, output_size=5)
model = model.to(device)

print(model)

dummy_input = torch.randn(16, 20).to(device)  # 16 samples, 20 features each
output = model(dummy_input)
print(f'\nInput shape: {dummy_input.shape}')  # [16, 20]
print(f'Output shape: {output.shape}')        # [16, 5]


MyFirstNetwork(
  (fc1): Linear(in_features=20, out_features=64, bias=True)
  (bn1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (fc2): Linear(in_features=64, out_features=32, bias=True)
  (bn2): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (fc3): Linear(in_features=32, out_features=5, bias=True)
  (dropout): Dropout(p=0.3, inplace=False)
)

Input shape: torch.Size([16, 20])
Output shape: torch.Size([16, 5])


## Section 5 - Loss Functions and Optimizers

A loss function measures how wrong the model's predictions are.
It outputs a single number called the loss:
- High loss = model is making big mistakes
- Low loss = model is doing well
The goal of training is to minimize this loss.

An optimizer looks at the gradients and decides how to update the model's weights to reduce the loss.

Common optimizers:
- SGD: simple and classic
- Adam: the most popular choice for most tasks
- AdamW: Adam with better weight regularization, great default

The learning rate controls how big each update step is.
Too high: training is unstable. Too low: training is very slow.
Typical range: 0.0001 to 0.01

In [11]:
# Common loss functions

# MSE Loss: for regression (predicting a number)
# MSE = Mean Squared Error = average of (predicted - actual) squared
mse_loss = nn.MSELoss()

predictions = torch.tensor([2.5, 3.0, 4.5, 1.0])
targets     = torch.tensor([3.0, 3.0, 4.0, 1.5])

loss = mse_loss(predictions, targets)
print(f'MSE Loss: {loss.item():.4f}')

# Cross Entropy Loss: for classification (predicting a category)
# Used when output is one of N categories
ce_loss = nn.CrossEntropyLoss()

# Model outputs raw scores (logits) for 3 classes
logits = torch.tensor([[2.0, 1.0, 0.1],   # model thinks class 0 most likely
                        [0.5, 2.5, 0.3]])  # model thinks class 1 most likely
labels = torch.tensor([0, 1])  # correct answers

loss = ce_loss(logits, labels)
print(f'\nCross Entropy Loss: {loss.item():.4f}')

# BCE Loss: Binary Cross Entropy for yes/no classification
bce_loss = nn.BCEWithLogitsLoss()  # applies sigmoid internally

pred_logits = torch.tensor([2.0, -1.5, 0.8, -0.2])
true_labels = torch.tensor([1.0,  0.0, 1.0,  0.0])

loss = bce_loss(pred_logits, true_labels)
print(f'\nBCE Loss: {loss.item():.4f}')


MSE Loss: 0.1875

Cross Entropy Loss: 0.3185

BCE Loss: 0.3244


In [12]:
# Optimizers

simple_model = nn.Sequential(nn.Linear(5, 3), nn.ReLU(), nn.Linear(3, 1))

# SGD: simplest optimizer
# Rule: weight = weight - learning_rate * gradient
# momentum: adds a fraction of the last update to help escape flat regions
sgd = optim.SGD(simple_model.parameters(), lr=0.01, momentum=0.9)
print('SGD optimizer created')

# Adam: most popular optimizer
# Adapts the learning rate for each parameter individually
adam = optim.Adam(simple_model.parameters(), lr=0.001, weight_decay=1e-4)
print('Adam optimizer created')

# AdamW: slight improvement over Adam with better weight regularization
# Usually the best default choice
adamw = optim.AdamW(simple_model.parameters(), lr=0.001, weight_decay=0.01)
print('AdamW optimizer created')

print('\nWhich to use?')
print('  Experimenting: Adam with lr=0.001')
print('  Production:    AdamW with lr=0.001')
print('  Large batches: SGD with momentum and a learning rate schedule')


SGD optimizer created
Adam optimizer created
AdamW optimizer created

Which to use?
  Experimenting: Adam with lr=0.001
  Production:    AdamW with lr=0.001
  Large batches: SGD with momentum and a learning rate schedule


In [13]:
# Learning Rate Schedulers
# A scheduler reduces the learning rate during training.
# Early in training, big steps are fine.
# Later, we need smaller steps to fine-tune without overshooting.

model_for_sched = nn.Linear(10, 1)
optimizer = optim.Adam(model_for_sched.parameters(), lr=0.1)

# StepLR: multiply LR by gamma every step_size epochs
step_scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=10, gamma=0.5)

print('StepLR schedule (LR every 10 epochs):')
lrs = []
for epoch in range(50):
    lrs.append(optimizer.param_groups[0]['lr'])
    step_scheduler.step()

for i in [0, 9, 10, 19, 20, 29, 40, 49]:
    print(f'  Epoch {i+1:2d}: LR = {lrs[i]:.6f}')

# CosineAnnealingLR: reduces LR following a smooth cosine curve
optimizer = optim.Adam(model_for_sched.parameters(), lr=0.1)
cosine_scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=50, eta_min=1e-6)

print('\nCosineAnnealing schedule (every 10 epochs):')
for epoch in range(50):
    if epoch % 10 == 0:
        print(f'  Epoch {epoch:2d}: LR = {optimizer.param_groups[0]["lr"]:.6f}')
    cosine_scheduler.step()


StepLR schedule (LR every 10 epochs):
  Epoch  1: LR = 0.100000
  Epoch 10: LR = 0.100000
  Epoch 11: LR = 0.050000
  Epoch 20: LR = 0.050000
  Epoch 21: LR = 0.025000
  Epoch 30: LR = 0.025000
  Epoch 41: LR = 0.006250
  Epoch 50: LR = 0.006250

CosineAnnealing schedule (every 10 epochs):
  Epoch  0: LR = 0.100000
  Epoch 10: LR = 0.090451
  Epoch 20: LR = 0.065451
  Epoch 30: LR = 0.034550
  Epoch 40: LR = 0.009550


C:\Users\abhis\AppData\Local\Temp\ipykernel_22360\1079257069.py:16: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  step_scheduler.step()
C:\Users\abhis\AppData\Local\Temp\ipykernel_22360\1079257069.py:29: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  cosine_scheduler.step()


## Section 6 - The Training Loop

The training loop is the heart of machine learning. It runs for many epochs (full passes through the training data).

Each epoch:
1. Forward pass: feed data through the model to get predictions
2. Compute loss: measure how wrong the predictions are
3. Backward pass: compute gradients using .backward()
4. Update weights: optimizer adjusts weights to reduce loss
5. Zero gradients: clear gradients for the next iteration

This cycle slowly pushes the model's weights toward values that minimize the loss.

In [14]:
import torch

# Create some simple fake data for a regression problem
torch.manual_seed(42)
n_samples = 200

# True relationship: y = 2*x1 + (-3)*x2 + 1.5*x3 + noise
X = torch.randn(n_samples, 3)
true_weights = torch.tensor([2.0, -3.0, 1.5])
y = X @ true_weights + 0.5 * torch.randn(n_samples)
y = y.unsqueeze(1)  # make shape [200, 1] instead of [200]

print(f'Input X shape: {X.shape}')
print(f'Target y shape: {y.shape}')
print(f'True weights the model needs to learn: {true_weights.tolist()}')


Input X shape: torch.Size([200, 3])
Target y shape: torch.Size([200, 1])
True weights the model needs to learn: [2.0, -3.0, 1.5]


In [15]:
# Build a simple model
regression_model = nn.Sequential(
    nn.Linear(3, 16),
    nn.ReLU(),
    nn.Linear(16, 1)  # output is a single number
).to(device)

criterion = nn.MSELoss()
optimizer = optim.Adam(regression_model.parameters(), lr=0.01)

X_dev = X.to(device)
y_dev = y.to(device)

print('Starting training...')

for epoch in range(100):

    # Step 1: set model to training mode
    # This enables Dropout and BatchNorm training behavior
    regression_model.train()

    # Step 2: forward pass - get predictions
    predictions = regression_model(X_dev)

    # Step 3: compute loss
    loss = criterion(predictions, y_dev)

    # Step 4: zero old gradients before computing new ones
    # If you skip this, gradients from the last step accumulate (wrong!)
    optimizer.zero_grad()

    # Step 5: backward pass - compute gradients
    loss.backward()

    # Step 6: update weights using computed gradients
    optimizer.step()

    if (epoch + 1) % 20 == 0:
        print(f'Epoch {epoch+1:3d}/100 | Loss: {loss.item():.4f}')

print('\nTraining complete!')


Starting training...
Epoch  20/100 | Loss: 8.7507
Epoch  40/100 | Loss: 2.3232
Epoch  60/100 | Loss: 0.5469
Epoch  80/100 | Loss: 0.3892
Epoch 100/100 | Loss: 0.3357

Training complete!


## Section 7 - Datasets and DataLoaders

In real projects, data is too large to fit in memory all at once.
We load it in small chunks called batches.

PyTorch has two classes for this:
- Dataset: holds your data and knows how to get one sample at a time
- DataLoader: wraps a Dataset and handles batching, shuffling, and loading in parallel

To create a custom Dataset you write a class with three methods:
- __init__: load or store your data
- __len__: return the total number of samples
- __getitem__: return one sample given its index

In [16]:
from torch.utils.data import Dataset, DataLoader, random_split

class MyDataset(Dataset):

    def __init__(self, n_samples=500):
        # Create 4 features from random numbers
        self.X = torch.randn(n_samples, 4)

        # Create labels based on a simple rule:
        # class 0: sum of features < -0.5
        # class 1: -0.5 <= sum <= 0.5
        # class 2: sum > 0.5
        s = self.X.sum(dim=1)
        self.y = torch.zeros(n_samples, dtype=torch.long)
        self.y[s > 0.5] = 2
        self.y[(s >= -0.5) & (s <= 0.5)] = 1

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        # Return one sample: (features, label)
        return self.X[idx], self.y[idx]


dataset = MyDataset(n_samples=500)
print(f'Dataset size: {len(dataset)} samples')

sample_x, sample_y = dataset[0]
print(f'Sample 0: features={sample_x}, label={sample_y}')

# Split into 80% train, 20% validation
train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size
train_dataset, val_dataset = random_split(dataset, [train_size, val_size])
print(f'\nTrain set: {len(train_dataset)} samples')
print(f'Val set:   {len(val_dataset)} samples')


Dataset size: 500 samples
Sample 0: features=tensor([-1.0779,  0.8849, -0.8342,  1.0301]), label=1

Train set: 400 samples
Val set:   100 samples


In [17]:
# Create DataLoaders

train_loader = DataLoader(
    train_dataset,
    batch_size=32,   # process 32 samples at once
    shuffle=True,    # shuffle every epoch to prevent order bias
    num_workers=0    # 0 = no multiprocessing (increase in real projects)
)

val_loader = DataLoader(
    val_dataset,
    batch_size=32,
    shuffle=False,   # do not shuffle validation - order does not matter
    num_workers=0
)

print(f'Train loader: {len(train_loader)} batches of 32')
print(f'Val loader:   {len(val_loader)} batches of 32')

# Check one batch
batch_x, batch_y = next(iter(train_loader))
print(f'\nOne batch:')
print(f'  Features shape: {batch_x.shape}')  # [32, 4]
print(f'  Labels shape:   {batch_y.shape}')  # [32]


Train loader: 13 batches of 32
Val loader:   4 batches of 32

One batch:
  Features shape: torch.Size([32, 4])
  Labels shape:   torch.Size([32])


In [18]:
# Full training loop with DataLoader

classifier = nn.Sequential(
    nn.Linear(4, 32),
    nn.ReLU(),
    nn.Linear(32, 16),
    nn.ReLU(),
    nn.Linear(16, 3)
).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(classifier.parameters(), lr=0.001)

train_losses, val_losses, val_accs = [], [], []

for epoch in range(20):

    # Training phase
    classifier.train()
    epoch_train_loss = 0.0

    for batch_x, batch_y in train_loader:
        batch_x = batch_x.to(device)
        batch_y = batch_y.to(device)

        optimizer.zero_grad()
        outputs = classifier(batch_x)
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()

        epoch_train_loss += loss.item()

    avg_train_loss = epoch_train_loss / len(train_loader)

    # Validation phase
    classifier.eval()
    epoch_val_loss = 0.0
    correct = 0
    total = 0

    with torch.no_grad():  # disable gradient tracking during validation
        for batch_x, batch_y in val_loader:
            batch_x = batch_x.to(device)
            batch_y = batch_y.to(device)

            outputs = classifier(batch_x)
            loss = criterion(outputs, batch_y)
            epoch_val_loss += loss.item()

            predicted = outputs.argmax(dim=1)
            correct += (predicted == batch_y).sum().item()
            total += batch_y.size(0)

    avg_val_loss = epoch_val_loss / len(val_loader)
    val_accuracy = 100 * correct / total

    train_losses.append(avg_train_loss)
    val_losses.append(avg_val_loss)
    val_accs.append(val_accuracy)

    if (epoch + 1) % 5 == 0:
        print(f'Epoch {epoch+1:2d}/20 | Train Loss: {avg_train_loss:.4f} | Val Loss: {avg_val_loss:.4f} | Val Acc: {val_accuracy:.1f}%')


Epoch  5/20 | Train Loss: 0.8600 | Val Loss: 0.8661 | Val Acc: 75.0%
Epoch 10/20 | Train Loss: 0.5158 | Val Loss: 0.5458 | Val Acc: 78.0%
Epoch 15/20 | Train Loss: 0.3402 | Val Loss: 0.3851 | Val Acc: 86.0%
Epoch 20/20 | Train Loss: 0.2401 | Val Loss: 0.2900 | Val Acc: 92.0%


## Part 1 Complete

We have now understand the fundamentals of PyTorch:

- Tensors: multi-dimensional arrays, the basic data structure in PyTorch
- Autograd: PyTorch tracks operations and computes gradients automatically with .backward()
- nn.Module: base class for all neural networks
- Loss Functions: MSE for regression, CrossEntropy for multi-class, BCE for binary
- Optimizers: Adam/AdamW are great defaults
- Training Loop: Forward -> Loss -> Zero Grad -> Backward -> Update -> Repeat
- DataLoader: efficiently loads data in shuffled batches


Open Part 2 when you are ready for CNNs, RNNs, Transfer Learning, and more.